# Site settings
title: Tao Dong, PhD | Human-Computer Interaction | Ubiquitous Computing | User Experience | Design
tag_text: Tao Dong, PhD
description: This is Tao Dong's personal website.
# Build settings
markdown: kramdown

exclude: ["README.md"]
